from enum import Enum


class TimeNature(str, Enum):
    FACE_PUBLIC = "FACE_PUBLIC"
    PREPARATION = "PREPARATION"
    TRAVEL = "TRAVEL"
    COORDINATION = "COORDINATION"
    MEETING = "MEETING"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    STAGE_OBSERVATION = "STAGE_OBSERVATION"
    VOLUNTEER = "VOLUNTEER"
