from enum import Enum


class Permission(str, Enum):
    READ_CONTRACTS = "READ_CONTRACTS"
    EDIT_CONTRACTS = "EDIT_CONTRACTS"
    READ_ASSIGNMENTS = "READ_ASSIGNMENTS"
    EDIT_ASSIGNMENTS = "EDIT_ASSIGNMENTS"
    READ_CONTROLS = "READ_CONTROLS"
    READ_SENSITIVE_HISTORY = "READ_SENSITIVE_HISTORY"
    EXPORT_SENSITIVE_DATA = "EXPORT_SENSITIVE_DATA"
    MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS"
