from enum import Enum


class RoleName(str, Enum):
    DIRECTION = "DIRECTION"
    RH = "RH"
    COMPTABILITE = "COMPTABILITE"
    DIRECTION_ADJOINTE = "DIRECTION_ADJOINTE"
    COORDINATION_PLANNING = "COORDINATION_PLANNING"
    BENEVOLE_DIRIGEANT = "BENEVOLE_DIRIGEANT"
