CREATE TABLE IF NOT EXISTS time_organizations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(64) NOT NULL UNIQUE,
    label VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT 1
);
