CREATE TABLE IF NOT EXISTS contracts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER NOT NULL,
    contract_type_id INTEGER NOT NULL,
    employment_regime_id INTEGER NOT NULL,
    time_organization_id INTEGER,
    start_date DATE NOT NULL,
    end_date DATE,
    annual_target_minutes INTEGER,
    monthly_smoothed_minutes INTEGER,
    weekly_reference_minutes INTEGER,
    work_quota DECIMAL(6,3),
    ccns_classification_id INTEGER,
    salary_grid_id INTEGER,
    base_remuneration DECIMAL(12,2),
    remuneration_unit VARCHAR(32),
    contract_status VARCHAR(64),
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (contract_type_id) REFERENCES contract_types(id),
    FOREIGN KEY (employment_regime_id) REFERENCES employment_regimes(id),
    FOREIGN KEY (time_organization_id) REFERENCES time_organizations(id)
);
