CREATE TABLE IF NOT EXISTS assignments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    internal_code VARCHAR(64) UNIQUE,
    person_id INTEGER NOT NULL,
    period_id INTEGER,
    activity_id INTEGER,
    place_id INTEGER,
    timeslot_id INTEGER,
    assignment_date DATE NOT NULL,
    entry_type VARCHAR(64),
    activity_title VARCHAR(255),
    start_time VARCHAR(8),
    end_time VARCHAR(8),
    break_minutes INTEGER,
    gross_minutes INTEGER,
    retained_minutes INTEGER,
    time_nature_id INTEGER,
    prep_ratio DECIMAL(8,4),
    prep_auto_minutes INTEGER,
    contract_id INTEGER,
    pfmp_id INTEGER,
    service_civique_id INTEGER,
    benevolat_id INTEGER,
    status VARCHAR(64),
    validation_status VARCHAR(64),
    is_locked BOOLEAN NOT NULL DEFAULT 0,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (period_id) REFERENCES periods(id),
    FOREIGN KEY (activity_id) REFERENCES activities(id),
    FOREIGN KEY (place_id) REFERENCES places(id),
    FOREIGN KEY (timeslot_id) REFERENCES timeslots(id),
    FOREIGN KEY (time_nature_id) REFERENCES time_natures(id),
    FOREIGN KEY (contract_id) REFERENCES contracts(id)
);
