from enum import Enum


class EmploymentRegime(str, Enum):
    CCNS_STANDARD = "CCNS_STANDARD"
    CCNS_MODULATION = "CCNS_MODULATION"
    CCNS_CDII = "CCNS_CDII"
    APPRENTICE = "APPRENTICE"
    CEE = "CEE"
    PEC_CUI_CAE = "PEC_CUI_CAE"
    SERVICE_CIVIQUE = "SERVICE_CIVIQUE"
    STAGE_PFMP = "STAGE_PFMP"
    VOLUNTEER = "VOLUNTEER"
    MANUAL_OUTSIDE_SCOPE = "MANUAL_OUTSIDE_SCOPE"
