from enum import Enum


class TimeOrganization(str, Enum):
    WEEKLY_CONSTANT = "WEEKLY_CONSTANT"
    ANNUALIZATION = "ANNUALIZATION"
    MODULATION = "MODULATION"
    INTERMITTENCE = "INTERMITTENCE"
    DAILY_CEE = "DAILY_CEE"
    STAGE_PFMP = "STAGE_PFMP"
    VOLUNTEER_COMMITMENT = "VOLUNTEER_COMMITMENT"
